//! Position types: the agent's read on the world, with challenge history.

use serde::{Deserialize, Serialize};

/// A short, plain-text statement of the world's state.
///
/// Tracks the accepted text and the history of attempts that were challenged along the way.
/// The challenge history captures alignment gaps in the collaboration, not agent failures.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Position {
    /// The accepted position text.
    pub text: String,

    /// Prior attempts that were challenged before arriving at the accepted text.
    pub history: Vec<PositionAttempt>,
}

/// A single attempt at stating a position, possibly challenged.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PositionAttempt {
    /// The position text that was proposed.
    pub text: String,

    /// Who produced this text.
    pub source: PositionSource,

    /// Feedback that caused this attempt to be rejected.
    /// Present on challenged attempts, absent on the final accepted one.
    pub challenged_with: Option<String>,
}

/// Who produced a position's text.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind")]
pub enum PositionSource {
    /// Generated by the LLM.
    Agent,

    /// Written or edited by the user.
    User,
}
