//! Reading types: the interpretation of what was observed, with challenge history.

use serde::{Deserialize, Serialize};

/// A short, plain-text interpretation of the world's state.
///
/// Tracks the accepted text and the history of attempts that were challenged along the way.
/// The challenge history captures alignment gaps in the collaboration, not agent failures.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Reading {
    /// The accepted reading text.
    pub text: String,

    /// Prior attempts that were challenged before arriving at the accepted text.
    pub history: Vec<ReadingAttempt>,
}

/// A single attempt at stating a reading, possibly challenged.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ReadingAttempt {
    /// The reading text that was proposed.
    pub text: String,

    /// Who produced this text.
    pub source: ReadingSource,

    /// Feedback that caused this attempt to be rejected.
    /// Present on challenged attempts, absent on the final accepted one.
    pub challenged_with: Option<String>,
}

/// Who produced a reading's text.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "camelCase")]
pub enum ReadingSource {
    /// Generated by the LLM.
    Agent,

    /// Written or edited by the user.
    User,
}
